name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 30

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Conductor (development mode)
      run: ./tools/install-dev.sh --ci
    - name: Check Formatting (black)
      run: ./tools/check-code.sh format
    - name: Lint (pylint)
      run: ./tools/check-code.sh lint
    - name: Type Check (mypy)
      run: ./tools/check-code.sh types
