# The purpose of this workflow is to ensure we can build the website
# successfully.

name: Test Website Build

on:
  push:
    branches: [ master ]
    paths:
    - 'website/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'website/**'
  workflow_dispatch: {}

jobs:
  build_website:
    name: Test Website Build
    timeout-minutes: 30

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set Up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Website Build Script
      run: ./tools/build-website.sh --install-deps
